# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hoa Mai
description:      'DevOps Engineer'
url:              https://hoadinhmai.github.io
baseurl:          
# https://github.com/github/pages-gem/issues/460

author:
  name:           'Hoa Mai'
  url:            https://hdm.cloud

plugins:
  - jekyll-paginate
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hoadinhmai/hoadinhmai.github.io
